#!/bin/sh
#
# PATHOS PeepingPanels Application
# auto-start of peeping-panels-peep
#

stop(){
        echo "stopping"
        kill $(cat /tmp/peepingPanels.pid)
        rm /tmp/peepingPanels.pid
}

start(){
        if [ -s /tmp/peepingPanels.pid ]; then
                stop
        fi
        echo "starting peepingPanels"
        /opt/pathos/bin/peeping-panels-peep i &
        echo "pid = $!"
        echo "$!" > /tmp/peepingPanels.pid
}

restart(){
        stop
        start
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart|reload)
                restart
                ;;

        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1

esac

exit $?

#
